# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Mashour - MS Azure Subscription - 558d32d5-3bab-45b9-b43d-a8c630b9dace - 72f988bf-86f1-41af-91ab-2d7cd011db47 ; alfonsod - MS Azure Subscription - 59ef6ed9-9c98-4b31-b7b9-f879439286bb - 72f988bf-86f1-41af-91ab-2d7cd011db47'
    ScriptType: 'InlineScript'
    Inline: |
      # You can write your azure powershell scripts inline here. 
      # You can also pass predefined and custom variables to this script using arguments
      
      $workspaceID=/subscriptions/558d32d5-3bab-45b9-b43d-a8c630b9dace/resourceGroups/NetworkWatcherRG/providers/Microsoft.OperationalInsights/workspaces/alfonsodtestaudit
      
      Set-AzSqlServerAudit -ResourceGroupName "alfonsodRG" -ServerName "alfonsodazdb" -LogAnalyticsTargetState Enabled -WorkspaceResourceId $workspaceID
    
    azurePowerShellVersion: 'LatestVersion'
